### PR TITLE
fix bug caused by lack of user info before task is added

### LINKED ISSUE #69: adding task when user hasn't saved user info causes an error
Now that tasks are added with a parent user entity, the user entity must exist before going through the add servlet task. Currently for new users without userInfo saved tasks are added first and then their user info.

### PR DESCRIPTION
**Pull request by poncem91**
Fixes #69

### CODE REVIEW

**Comment by poncem91** [comment]
> LGTM! But I would suggest creating an issue for a different implementation, just to remind us after the MVP.

Good idea! I'll add that now :)

**Comment by poncem91** [comment]
> This breaks a couple of the tests (`mvn test`):
> 
> ```
> Failed tests: 
>   TaskServletTest.singleInputDoPostTest:103 expected:<1> but was:<0>
>   TaskServletTest.multipleInputDoPostTest:133 expected:<1> but was:<0>
> 
> Tests run: 8, Failures: 2, Errors: 0, Skipped: 0
> ```

I believe Leonard has made changes to fix this/is making changes to fix this on PR #66 - the tests were missing the category input that recently got added to the add tasks form, so they fail on the master branch as well currently (I think branches changing the tests and adding the category might've been approved and merged around the same time). 

Should I wait until he's merged the branch onto master and merge those changes onto this branch?

**Comment by peap** [comment]
> Should I wait until he's merged the branch onto master and merge those changes onto this branch?

Sounds good - #66 was just merged into the main line.

**Comment by poncem91** [comment]
> > Should I wait until he's merged the branch onto master and merge those changes onto this branch?
> 
> Sounds good - #66 was just merged into the main line.

Just merged those changes onto this branch so the tests don't break anymore :)

**Pull request merged**
